var sld = '<?xml version="1.0" encoding="ISO-8859-1"?>'
sld += '<StyledLayerDescriptor version="1.0.0" '
sld +=     'xsi:schemaLocation="http://www.opengis.net/sld StyledLayerDescriptor.xsd"' 
sld +=     'xmlns="http://www.opengis.net/sld"'
sld +=     'xmlns:ogc="http://www.opengis.net/ogc"'
sld +=    ' xmlns:xlink="http://www.w3.org/1999/xlink"' 
sld +=     'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">'
sld +=   '<NamedLayer>'
sld +=     '<Name>Simple polygon</Name>'
sld +=     '<UserStyle>'
sld +=       '<Title>SLD Cook Book: Simple polygon</Title>'
sld +=       '<FeatureTypeStyle>'
sld +=         '<Rule>'
sld +=           '<PolygonSymbolizer>'
sld +=             '<Fill>'
sld +=               '<CssParameter name="fill">#000080</CssParameter>'
sld +=             '</Fill>'
sld +=           '</PolygonSymbolizer>'
sld +=         '</Rule>'
sld +=       '</FeatureTypeStyle>'
sld +=     '</UserStyle>'
sld +=   '</NamedLayer>'
sld += '</StyledLayerDescriptor>'
